version: "3.8"

networks:
    default:
        name: inception_net

services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: nginx
        ports:
            - 443:443
        depends_on:
            - wordpress
            - mariadb
        volumes:
            - wordpress_data:/var/www/html
        restart: always
    wordpress:
        init: true
        container_name: wordpress
        image: wordpress
        build: 
            context: ./wordpress
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - wordpress_data:/var/www/html
        restart: always
    mariadb:
        init: true
        container_name: mariadb
        image: mariadb
        build: 
            context: ./mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        restart: always
    redis:
        init: true
        container_name: redis
        image: redis
        build: ./bonus/redis
        depends_on:
            - wordpress
        env_file:
            - .env
        volumes:
            - wordpress_data:/var/www/html
        restart: always
    ftp:
        init: true
        container_name: ftp
        image: ftp
        build: ./bonus/FTP_server
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        env_file:
            - .env
        restart: always
    adminer:
        container_name: adminer
        image: adminer
        build: ./bonus/Adminer
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html
        restart: on-failure
    static_web:
        container_name: static_web
        image: static_web
        build: ./bonus/static_web
        volumes:
            - hugo_data:/var/www/hugo
        restart: on-failure
    hugo:
        init: true
        container_name: hugo
        image: hugo
        build: ./bonus/hugo
        depends_on:
            - static_web
        ports:
            - "1313:1313"
        env_file:
            - .env
        volumes:
            - hugo_data:/var/www/hugo
        restart: always

volumes:
    wordpress_data:
        driver: local
        driver_opts:
            o: "bind"
            type: "none"
            device: "/home/eabdelha/data/wordpress"
    mariadb_data:
        driver: local
        driver_opts:
            o: "bind"
            type: "none"
            device: "/home/eabdelha/data/mariadb"
    hugo_data:
        driver: local
        driver_opts:
            o: "bind"
            type: "none"
            device: "/home/eabdelha/data/hugo"